sudo: required

notifications:
  slack: go-mi:Rw8QWzrSzlolt3Tx1AAEeFYJ

before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install g++
  - sudo apt-get install cpputest
  - sudo apt-get install python-dev
  - sudo apt-get install clang-format
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
# Build steps
script:
  - ./check_format.sh ${TRAVIS_PULL_REQUEST_BRANCH} ${TRAVIS_BRANCH} 
  - echo ${TRAVIS_PULL_REQUEST_BRANCH} ${TRAVIS_BRANCH}
  - mkdir build
  - g++ tests/*.cpp -lCppUTest -o build/tests-bin.out
  - ./build/tests-bin.out
