sudo: required

notifications:
  slack: go-mi:Rw8QWzrSzlolt3Tx1AAEeFYJ

before_install:
  - sudo apt-get install libao-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install g++
  - sudo apt-get install cpputest
  - sudo apt-get install python-dev
  
# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - g++
  
install:
  - sudo pip install cpplint
# Build steps
script:
  - cpplint --recursive --exclude=./tests/* --filter=-whitespace,-legal,-build/c++11,-build/include_subdir .
  - mkdir build
  - g++ tests/*.cpp -lCppUTest -o build/tests-bin.out
  - ./build/tests-bin.out